export const ENDPOINTS = {
  TOKEN: '/token',
  DELETE: '/webapi/external/delete',
  DELETE_MULTIPLE: '/webapi/external/deleteMultiple',
  FETCH: '/webapi/external/fetch',
  GET: '/webapi/external/get',
  GET_MULTIPLE: '/webapi/external/getMultiple',
  SAVE_ALL: '/webapi/external/saveAll',
  FETCH_ATTACHMENT: '/webapi/external/fetchAttachment',
  SAVE_ATTACHMENT: '/webapi/external/saveAttachmentFormData',
  FETCH_SINGLE_DOCUMENT: '/webapi/external/fetchSingleDocument',
  SAVE_SINGLE_DOCUMENT: '/webapi/external/saveSingleDocumentFormData',
  GET_GENERIC_ENTITIES: '/webapi/external/GetGenericEntities',
  GET_GENERIC_PROPERTIES: '/webapi/external/GetGenericProperties',
  GET_GENERIC_VIEWS: '/webapi/external/GetGenericViews',
  GET_GENERIC_VIEW_FIELDS: '/webapi/external/GetGenericViewFields',
};
