export interface ENGINE4Options {
  /**
   * The base URL of the ENGINE4 server.
   *
   * @since 0.0.1
   * @example https://prod.engine4.io/
   */
  baseUrl: string;
}

/**
 * @since 0.0.1
 */
export type AuthenticateOptions =
  PasswordAuthenticateOptions | ClientCredentialsAuthenticateOptions;

/**
 * @since 0.1.0
 */
export interface BaseAuthenticateOptions {
  /**
   * The client id of the user to authenticate.
   *
   * @since 0.0.1
   */
  clientId: string;
  /**
   * Whether a refresh token should be returned.
   *
   * @since 0.1.0
   * @default false
   */
  withRefreshToken?: boolean;
}

/**
 * Authenticate with username and password (`password` grant).
 *
 * @since 0.1.0
 */
export interface PasswordAuthenticateOptions extends BaseAuthenticateOptions {
  /**
   * The username of the user to authenticate.
   *
   * @since 0.0.1
   */
  username: string;
  /**
   * The password of the user to authenticate.
   *
   * @since 0.0.1
   */
  password: string;
}

/**
 * Authenticate with a client secret (`client_credentials` grant).
 *
 * @since 0.1.0
 */
export interface ClientCredentialsAuthenticateOptions extends BaseAuthenticateOptions {
  /**
   * The client secret.
   *
   * @since 0.1.0
   */
  clientSecret: string;
}

/**
 * @since 0.0.1
 */
export interface AuthenticateResult {
  /**
   * The access token.
   *
   * @since 0.0.1
   */
  accessToken: string;
  /**
   * The amount of time in seconds that the access token is valid for.
   *
   * @since 0.0.1
   */
  expiresIn: number;
  /**
   * The refresh token.
   *
   * Only returned if `withRefreshToken` is `true`.
   *
   * @since 0.0.1
   */
  refreshToken?: string;
  /**
   * The scope of the token.
   *
   * @since 0.0.1
   */
  scope: string;
  /**
   * The type of token.
   *
   * @since 0.0.1
   */
  tokenType: 'Bearer';
}

export interface BaseOptions {
  /**
   * The access token to use to authenticate the request.
   *
   * This token can be generated by calling the `authenticate` method.
   *
   * @since 0.0.1
   */
  accessToken: string;
}

/**
 * @since 0.1.0
 */
export interface ConvertCustomDataOptions {
  /**
   * If `false`, custom values are returned with their underlying data type
   * (e.g. `false` or `12`) instead of strings (e.g. `'0'` or `'12'`).
   *
   * @since 0.1.0
   * @default true
   */
  convertAllCustomDataToStrings?: boolean;
}

/**
 * The type of custom values in results, depending on `convertAllCustomDataToStrings`.
 *
 * @since 0.1.0
 */
export type CustomValueOf<T extends ConvertCustomDataOptions> =
  'convertAllCustomDataToStrings' extends keyof T
    ? false extends T['convertAllCustomDataToStrings']
      ? CustomValue
      : string
    : string;

/**
 * A custom value with its underlying data type.
 *
 * @since 0.1.0
 */
export type CustomValue = string | number | boolean | null;

/**
 * @since 0.0.1
 */
export interface DeleteOptions extends BaseOptions {
  /**
   * The ID of the entity to delete data from.
   *
   * @since 0.0.1
   */
  entityId: string;
  /**
   * The ID of the generic data element to delete.
   *
   * @since 0.0.1
   */
  dataId: string;
}

/**
 * @since 0.0.3
 */
export interface DeleteMultipleOptions extends BaseOptions {
  /**
   * The ID of the entity to delete data from.
   *
   * @since 0.0.3
   */
  entityId: string;
  /**
   * The IDs of the generic data elements to delete.
   *
   * @since 0.0.3
   */
  dataIds: string[];
}

/**
 * @since 0.0.1
 */
export interface FetchOptions extends BaseOptions, ConvertCustomDataOptions {
  /**
   * The ID of the entity to retrieve data from.
   *
   * @since 0.0.1
   */
  entityId: string;
  /**
   * The ID of a view to retrieve data through.
   *
   * If set, the results contain the fields of the view (including linked fields)
   * instead of all properties of the entity.
   *
   * @since 0.1.0
   */
  viewId?: string;
  /**
   * @since 0.0.1
   */
  filter?: FetchFilterOptions;
  /**
   * If `true`, only non-deleted records will be returned.
   * If `false`, only deleted records will be returned.
   * If `null`, all records will be returned.
   *
   * @since 0.0.1
   */
  isActive?: boolean | null;
  /**
   * The number of records to skip.
   *
   * @since 0.0.1
   */
  skip?: number;
  /**
   * @since 0.0.1
   */
  sorting?: FetchSortingOptions[];
  /**
   * The maximum number of records to return.
   *
   * @since 0.0.1
   */
  take?: number;
  /**
   * Whether the `CustomMax_XXX` values are returned.
   *
   * @since 0.0.1
   */
  withLongValues?: boolean;
}

/**
 * A single filter condition or a group of nested filters.
 *
 * @since 0.0.1
 */
export type FetchFilterOptions = FetchFilterCondition | FetchFilterGroup;

/**
 * A filter condition. The type of `value` depends on the `compareOperator`.
 *
 * @since 0.1.0
 */
export type FetchFilterCondition =
  FetchFilterValueCondition | FetchFilterInCondition | FetchFilterNullCondition;

/**
 * @since 0.1.0
 */
export interface BaseFetchFilterCondition {
  /**
   * The name of the generic column to filter on.
   *
   * @since 0.0.1
   */
  genericName: GenericColumnName;
}

/**
 * @since 0.1.0
 */
export interface FetchFilterValueCondition extends BaseFetchFilterCondition {
  /**
   * The operator to use to filter the results.
   *
   * @since 0.0.1
   */
  compareOperator: Exclude<
    CompareOperator,
    CompareOperator.In | CompareOperator.IsNull | CompareOperator.IsNotNull
  >;
  /**
   * The value to compare against.
   *
   * @since 0.0.1
   */
  value: string;
}

/**
 * @since 0.1.0
 */
export interface FetchFilterInCondition extends BaseFetchFilterCondition {
  /**
   * @since 0.1.0
   */
  compareOperator: CompareOperator.In;
  /**
   * The values to compare against.
   *
   * @since 0.1.0
   */
  value: string[];
}

/**
 * @since 0.1.0
 */
export interface FetchFilterNullCondition extends BaseFetchFilterCondition {
  /**
   * @since 0.1.0
   */
  compareOperator: CompareOperator.IsNull | CompareOperator.IsNotNull;
}

/**
 * @since 0.1.0
 */
export interface FetchFilterGroup {
  /**
   * How the filters of the group are combined.
   *
   * @since 0.1.0
   */
  logic: 'AND' | 'OR';
  /**
   * The filters of the group. Groups can be nested.
   *
   * @since 0.1.0
   */
  groups: FetchFilterOptions[];
}

/**
 * @since 0.0.1
 */
export interface FetchSortingOptions {
  /**
   * The name of the generic column to sort by.
   *
   * @since 0.0.1
   */
  genericName: GenericColumnName;
  /**
   * The direction to sort by.
   *
   * @since 0.0.1
   * @default 'asc'
   */
  sort: 'asc' | 'desc';
}

/**
 * @since 0.0.1
 */
export interface FetchResult<TValue extends CustomValue = string> {
  /**
   * The fetched generic data elements.
   *
   * @since 0.0.1
   */
  items: GenericDataElement<TValue>[];
}

/**
 * @since 0.0.1
 */
export interface GetOptions extends BaseOptions, ConvertCustomDataOptions {
  /**
   * The ID of the entity to retrieve data from.
   *
   * @since 0.0.1
   */
  entityId: string;
  /**
   * The ID of the generic data element to retrieve.
   *
   * @since 0.0.1
   */
  dataId: string;
}

/**
 * @since 0.0.1
 */
export interface GetResult<TValue extends CustomValue = string> {
  /**
   * The fetched generic data element.
   *
   * @since 0.0.1
   */
  item: GenericDataElement<TValue>;
}

/**
 * @since 0.0.3
 */
export interface GetMultipleOptions extends BaseOptions, ConvertCustomDataOptions {
  /**
   * The ID of the entity to retrieve data from.
   *
   * @since 0.0.3
   */
  entityId: string;
  /**
   * The IDs of the generic data elements to retrieve.
   *
   * @since 0.0.3
   */
  dataIds: string[];
}

/**
 * @since 0.0.3
 */
export interface GetMultipleResult<TValue extends CustomValue = string> {
  /**
   * The fetched generic data elements.
   *
   * @since 0.0.3
   */
  items: GenericDataElement<TValue>[];
}

/**
 * @since 0.0.1
 */
export interface SaveAllOptions extends BaseOptions {
  /**
   * The generic data elements to save.
   *
   * If a `DataId` is provided and exists, the element is updated.
   * Otherwise, a new element is created.
   *
   * @since 0.0.1
   */
  items: SaveItem[];
  /**
   * The return type of the saved generic data elements.
   *
   * @since 0.0.1
   * @default 'none'
   */
  returnType?: SaveAllReturnType;
}

/**
 * @since 0.1.0
 */
export type SaveAllReturnType = 'none' | 'dataId' | 'full';

/**
 * A generic data element to save. Only `EntityId` is required.
 *
 * @since 0.1.0
 */
export type SaveItem = Partial<GenericDataElement<CustomValue>> &
  Pick<GenericDataElement, 'EntityId'>;

/**
 * @since 0.0.1
 */
export interface SaveAllResult<TReturnType extends SaveAllReturnType | undefined = undefined> {
  /**
   * The saved generic data elements.
   *
   * Empty if `returnType` is `none`.
   * Only `DataId` and `EntityId` if `returnType` is `dataId`.
   *
   * @since 0.0.1
   */
  items: TReturnType extends 'full'
    ? GenericDataElement[]
    : TReturnType extends 'dataId'
      ? SavedItemReference[]
      : [];
}

/**
 * @since 0.1.0
 */
export type SavedItemReference = Pick<GenericDataElement, 'DataId' | 'EntityId'>;

/**
 * @since 0.0.4
 */
export interface FetchAttachmentOptions extends BaseOptions {
  /**
   * The ID of the attachment to fetch.
   *
   * @since 0.0.4
   */
  dataId: string;
}

/**
 * @since 0.0.4
 */
export interface FetchAttachmentResult {
  /**
   * The fetched attachment.
   *
   * @since 0.0.4
   */
  item: Buffer;
  /**
   * The file name of the attachment, if provided by the server.
   *
   * @since 0.1.0
   */
  filename?: string;
  /**
   * The MIME type of the attachment, if provided by the server.
   *
   * @since 0.1.0
   */
  mimeType?: string;
}

/**
 * @since 0.0.1
 */
export type GenericColumnName = keyof GenericDataElement;

/**
 * @since 0.0.1
 */
export interface GenericDataElement<TValue extends CustomValue = string> {
  /**
   * The display text of a dropdown (lookup) value, e.g. `Custom_004_DisplayValue`.
   *
   * @since 0.1.0
   */
  [displayValue: `Custom_${string}_DisplayValue`]: string | undefined;
  /**
   * @since 0.0.1
   */
  CreatedBy?: string;
  /**
   * @since 0.0.1
   */
  CreatedById?: string;
  /**
   * The creation date in ISO 8601 format.
   *
   * @since 0.1.0
   */
  CreatedDate?: string;
  /**
   * @since 0.0.1
   */
  Custom_001?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_002?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_003?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_004?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_005?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_006?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_007?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_008?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_009?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_010?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_011?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_012?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_013?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_014?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_015?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_016?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_017?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_018?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_019?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_020?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_021?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_022?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_023?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_024?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_025?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_026?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_027?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_028?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_029?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_030?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_031?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_032?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_033?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_034?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_035?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_036?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_037?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_038?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_039?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_040?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_041?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_042?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_043?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_044?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_045?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_046?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_047?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_048?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_049?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_050?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_051?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_052?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_053?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_054?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_055?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_056?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_057?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_058?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_059?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_060?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_061?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_062?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_063?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_064?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_065?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_066?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_067?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_068?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_069?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_070?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_071?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_072?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_073?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_074?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_075?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_076?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_077?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_078?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_079?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_080?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_081?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_082?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_083?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_084?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_085?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_086?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_087?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_088?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_089?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_090?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_091?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_092?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_093?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_094?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_095?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_096?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_097?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_098?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_099?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_100?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_101?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_102?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_103?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_104?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_105?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_106?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_107?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_108?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_109?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_110?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_111?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_112?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_113?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_114?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_115?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_116?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_117?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_118?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_119?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_120?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_121?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_122?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_123?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_124?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_125?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_126?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_127?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_128?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_129?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_130?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_131?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_132?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_133?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_134?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_135?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_136?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_137?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_138?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_139?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_140?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_141?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_142?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_143?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_144?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_145?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_146?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_147?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_148?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_149?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_150?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_151?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_152?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_153?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_154?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_155?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_156?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_157?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_158?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_159?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_160?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_161?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_162?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_163?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_164?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_165?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_166?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_167?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_168?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_169?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_170?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_171?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_172?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_173?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_174?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_175?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_176?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_177?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_178?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_179?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_180?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_181?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_182?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_183?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_184?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_185?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_186?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_187?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_188?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_189?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_190?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_191?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_192?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_193?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_194?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_195?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_196?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_197?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_198?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_199?: TValue;
  /**
   * @since 0.0.1
   */
  Custom_200?: TValue;
  /**
   * @since 0.0.1
   */
  CustomMax_001?: string;
  /**
   * @since 0.0.1
   */
  CustomMax_002?: string;
  /**
   * @since 0.0.1
   */
  CustomMax_003?: string;
  /**
   * @since 0.0.1
   */
  CustomMax_004?: string;
  /**
   * @since 0.0.1
   */
  CustomMax_005?: string;
  /**
   * @since 0.0.1
   */
  CustomMax_006?: string;
  /**
   * @since 0.0.1
   */
  DataId: string;
  /**
   * The display text of the element.
   *
   * @since 0.1.0
   */
  DisplayValue?: string;
  /**
   * @since 0.0.1
   */
  EntityId: string;
  /**
   * The entry time in ISO 8601 format.
   *
   * @since 0.1.0
   */
  EntryTime?: string;
  /**
   * Whether the user has write access to the element.
   *
   * @since 0.1.0
   */
  HasWriteAccess?: boolean;
  /**
   * @since 0.0.1
   */
  IsActive: boolean;
  /**
   * @since 0.1.0
   */
  MandatorId?: string;
  /**
   * @since 0.0.1
   */
  ModifiedBy?: string;
  /**
   * @since 0.0.1
   */
  ModifiedById?: string;
  /**
   * The modification date in ISO 8601 format.
   *
   * @since 0.1.0
   */
  ModifiedDate?: string;
  /**
   * @since 0.1.0
   */
  OrgUnitId?: string;
  /**
   * @since 0.1.0
   */
  TriggerStamp?: string;
  /**
   * @since 0.0.1
   */
  UserId: string;
  /**
   * The display name of the user.
   *
   * @since 0.1.0
   */
  UserDisplayName?: string;
}

export enum CompareOperator {
  Equal = '=',
  NotEqual = '!=',
  LessThan = '<',
  GreaterThan = '>',
  LessThanOrEqualTo = '<=',
  GreaterThanOrEqualTo = '>=',
  Like = 'LIKE',
  Contains = 'CONTAINS',
  IsNull = 'ISNULL',
  IsNotNull = 'ISNOTNULL',
  In = 'IN',
}
